# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c524411634a5b57204107103d3b6f491e442df53545249a5cff62cb6b76ee88ab6f0209787d33a31fe2951a7ef6ca4937a0f8e9df559d5f9821aa5efa5295d5a

test:
  secret_key_base: fffca6c43e5c526f1f1958bb61c238bbc22fb39c6d94fa4b9be8876afd2d9be1ffc5fad463eaeb17e152d68029f03679935347ea22921f013988c9b1e62e4dd3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
