user:
  email_max_length: 255
  name_max_length: 50
  password_min_length: 6
  avatar_size: 80
  hour_expired: 2
session:
  remember_me: "1"
micropost:
  avatar_size: 50
  per_page: 20
  max_size: 5
  max_content: 140
